### ISSUE TITLE
Spatial breaks on TK1

### ISSUE THREAD

**Issue by Atcold** [e-lab/Torch7-profiling#2]
```
ubuntu@tegra-ubuntu ~/Downloads/Torch7-profiling [master*]$ th profile-model.lua -m models/td-net-large.lua -h 1280 -w 720
Building Net Large model from model...
	
Convert network to cpu spatial	
/usr/local/bin/luajit: ./src/spatial.lua:69: attempt to call method 'cuda' (a nil value)
stack traceback:
	./src/spatial.lua:69: in function 'net_spatial'
	profile-model.lua:67: in main chunk
	[C]: in function 'dofile'
	/usr/local/lib/luarocks/rocks/trepl/scm-1/bin/th:131: in main chunk
	[C]: at 0x0000d055
```

**Comment by bmartini** [comment]
Vinayak and I worked on this problem while we were in California. We had a
fix and Vinay was meant to finish testing it and push it but I guess he
didn't do so. You can ask him if he still has assess to it.

The problem also exists in the apps/generic. Basically the spatial module
should not have to deal with cuda but should instead convert the cpu
network and then let the cuda conversion happen later.




On Wed, Jul 22, 2015 at 11:07 AM, Alfredo Canziani <notifications@github.com

**Comment by Atcold** [comment]
@vgokhale said I can track the problem and fix it myself.
I think, since you had already done so, this will take you less time.

**Comment by Atcold** [comment]
Do you think someone (@vgokhale or you) can get this fixed?

**Comment by vgokhale** [comment]
Fixed.

**Comment by Atcold** [comment]
@vgokhale thank you.
