### ISSUE TITLE
models in models/ do not work?

### ISSUE THREAD

**Issue by culurciello** [e-lab/Torch7-profiling#3]
eugenioculurciello@pal-nat186-149-74:~/Code/github/Torch7-profiling(master) $ th profile-model.lua --model models/td-net-large.lua 
Building Net Large model from model...
	
/Users/eugenioculurciello/torch/install/bin/luajit: bad argument #1 to '?' (expecting number or torch.FloatTensor or torch.FloatStorage at /Users/eugenioculurciello/torch/pkg/torch/generic/Tensor.c:1125)
stack traceback:
	[C]: at 0x0114c880
	[C]: in function 'FloatTensor'
	profile-model.lua:74: in main chunk
	[C]: in function 'dofile'
	...ello/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x0100e01ce0

**Comment by codeAC29** [comment]
You need to give the resolution also. I just saw that for the td-net-large.lua it only works for eye size.
Try this:
`th profile-model.lua --model models/td-net-large.lua --res 1x3x231x231`

**Comment by codeAC29** [comment]
`AlexNet` and `VGG` work for 231x231 only.
Other networks work for any resolution.
