### ISSUE TITLE
can you please add useful models

### ISSUE THREAD

**Issue by culurciello** [e-lab/Torch7-profiling#4]
Please remove all current models in "models/"
please add to models:
- Alexnet owt: https://github.com/e-lab/imagenet-multiGPU.torch/blob/master/models/alexnetowt.lua
- resnet: https://raw.githubusercontent.com/facebook/fb.resnet.torch/master/models/resnet.lua
- VGG: https://github.com/e-lab/imagenet-multiGPU.torch/blob/master/models/vggbn.lua
at least

**Comment by codeAC29** [comment]
Added all three of them
